### ISSUE TITLE
Document what actions are recorded in CloudTrail

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/aws-cloudtrail-user-guide#1]
The docs only list what services are supported in CloudTrail here: https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/cloudtrail-supported-services.md

You then have to try to figure out what actions of those services are recorded.  It would be helpful to know all actions that are actually recorded in CloudTrail.

**Comment by AWS-SF** [comment]
Hi Scott,

Each individual AWS service documents which of its APIs are supported in CloudTrail. You can find the list of topics for each service here: https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/cloudtrail-aws-service-specific-topics.md

That being said, it sounds like we could improve by making this clearer at the beginning of this topic, or by concatenating the two. We'll look into that.

Hope this helps, and thanks for pointing out the issue!

SF

**Comment by 0xdabbad00** [comment]
Unfortunately, it requires a fair bit of manual work to look through every service.  I did this manually in order to compile this list of what actions are recorded by CloudTrail: https://github.com/duo-labs/cloudtracker/blob/master/cloudtrail_supported_actions.txt

In order to find what calls are not recorded in CloudTrail, that can be diff'd against this list of all API actions: https://github.com/duo-labs/cloudtracker/blob/master/aws_api_list.txt

It is going to be annoying to try to keep that list updated without better support from AWS on this.

**Comment by AWS-SF** [comment]
Hi Scott,

I see what you mean. This is an excellent feature request, and I've submitted it to the CloudTrail team. Thank you for the suggestion!

SF

**Comment by 0xdabbad00** [comment]
Can we reopen this issue then please?

**Comment by AWS-SF** [comment]
Sure thing. I've reopened it so we can keep it on the radar.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
