### ISSUE TITLE
CloudTrail to ElasticSearch Service?

### ISSUE THREAD

**Issue by Jeeppler** [awsdocs/aws-cloudtrail-user-guide#11]
Is there a way to ship CloudTrail logs and events to ElasticSearch service?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
