### ISSUE TITLE
Document naming discrepancies between IAM privileges -> API calls -> CloudTrail

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/aws-cloudtrail-user-guide#2]
Some CloudTrail recorded events have different names than the IAM privileges or API calls associated with them. For example, usage of the IAM privilege `s3:ListAllMyBuckets` results in a CloudTrail event record of `ListBuckets`.  It would be helpful to have a list of translations between these as CloudTrail logs are often used to identify what IAM privileges are needed by actors, or what API calls were made.

**Comment by AWS-SF** [comment]
Hi Scott,

That's a great suggestion. This information should be included in each service's individual integration topic for CloudTrail (https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/cloudtrail-aws-service-specific-topics.md), but it's not something we've been tracking, and we should. 

Thanks for bringing this to our attention!  

SF

**Comment by IvanMwiruki** [comment]
I work on CloudTrail. The `eventName` field in CloudTrail events matches up to the public AWS api call. So the only discrepancy should be between IAM and api calls. It would be great if IAM aligned their privileges with api call but I have no idea what constraints they're working under.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
