### ISSUE TITLE
Missing value in "eventtype" attribute definition

### ISSUE THREAD

**Issue by madhavvishnubhatta** [awsdocs/aws-cloudtrail-user-guide#21]
Hi,

I am looking at this page: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html for the "eventtype" attribute.

It has 3 possible values listed:

>**`eventType`**  
Identifies the type of event that generated the event record\. This can be the one of the following values:   
>+ `AwsApiCall` – An API was called\. 
>+ `AwsServiceEvent` – The service generated an event related to your trail\. For example, this can occur when another account made a call with a resource that you own\. 
>+ `AwsConsoleSignin` – A user in your account \(root, IAM, federated, SAML, or SwitchRole\) signed in to the AWS Management Console\.

But when I update the alternate security contact on my AWS account, I see that the cloudtrail event record has a value of "AwsConsoleAction" for this "eventype" attribute. That value along with the definition of the scenarios when that "AwsConsoleAction" value will show up needs to be added as a 4th possible value.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
