### ISSUE TITLE
InsufficientS3BucketPolicyException error following documentation

### ISSUE THREAD

**Issue by tlliddle** [awsdocs/aws-cloudtrail-user-guide#24]
In the documentation for [Creating a trail for an organization with the AWS Command Line Interface](https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/cloudtrail-create-and-update-an-organizational-trail-by-using-the-aws-cli.md#create-or-update-an-amazon-s3-bucket-to-use-to-store-the-log-files-for-an-organization-trail) I created a bucket policy and run the command:
 `aws cloudtrail create-trail --name ct-name --s3-bucket-name bucketname --is-organization-trail --is-multi-region-trail`

I get the following error:
`An error occurred (InsufficientS3BucketPolicyException) when calling the CreateTrail operation: Incorrect S3 bucket policy is detected for bucket: bucketname`

I've compared the sample policy in the documentation to what I updated and everything seems correct.  Not sure what I'm missing.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
