### ISSUE TITLE
Markdown file create-s3-bucket-policy-for-cloudtrail.md doesn't match live documentation

### ISSUE THREAD

**Issue by adenot** [awsdocs/aws-cloudtrail-user-guide#25]
The page: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html contains a paragraph:

> As a security best practice, add an aws:SourceArn condition key to the Amazon S3 bucket policy. The IAM global condition key aws:SourceArn helps ensure that CloudTrail writes to the S3 bucket only for a specific trail or trails. The value of aws:SourceArn is always the ARN of the trail (or array of trail ARNs) that is using the bucket to store logs. Be sure to add the aws:SourceArn condition key on S3 bucket policies for existing trails.

Which does not exist in equivalent markdown file: https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/create-s3-bucket-policy-for-cloudtrail.md

**Comment by GitHubJillG** [comment]
Thanks for your feedback. I've closed this issue since the markdown in GitHub is now aligned with the document source.
