### ISSUE TITLE
Suggestions for common troubleshooting issues or problems

### ISSUE THREAD

**Issue by AWS-SF** [awsdocs/aws-cloudtrail-user-guide#6]
If you have any ideas about any common troubleshooting issues, problems, or tips and tricks that should be included in the AWS CloudTrail User Guide, please let me know! I'd love to hear about your troubleshooting tips and tricks you've used to find and fix problems, your favorite CloudTrail implementation tip, what you wish you'd known when you were just getting started, or anything else you'd care to share. If you're relatively new to CloudTrail, I'd also love to hear about your experience.

Please submit a pull request as explained here: https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/CONTRIBUTING.md

Thanks for helping improve the documentation! I look forward to hearing from you.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
